gamedirs_file: gamedirs.2011.json
#engine: sqlite
#sqlite_file: baseball.sqlite
engine: postgres
postgres_db: pypitches 
postgres_user: pypitches
postgres_password: slider
tables_file: baseball.sql
ignore_files: [inning_Scores.xml, inning_hit.xml]
